### ISSUE TITLE
how to cimpile essentia on visual studio 2017 / visual studio 2019

### ISSUE THREAD

**Issue by imiskolee** [MTG/essentia#1204] opened 2021-11-18 10:10 UTC
hi all:

I am looking for a solution for compiling it on visual studio 2017/2019 as a static library, because of My program needs  visual studio, so can not use MinGW.

did anyone has visual studio project or guide?

**Comment by dbogdanov** [comment] 2021-11-22 18:28
Duplicate of #330

**Closed by dbogdanov** 2021-11-22 18:28 UTC
