### ISSUE TITLE
Vibrato segmentation fault

### ISSUE THREAD

**Issue by minzwon** [MTG/essentia#580] opened 2017-03-31 15:22 UTC
import essentia.standard as es
audioFile = './Audio/001.mp3'
audioLoader = es.EqloudLoader(filename=audioFile)
audio = audioLoader()
melodia = es.PredominantPitchMelodia(hopSize=32)
[pitch,confidence] = melodia(audio)
vib = es.Vibrato(minExtend=1,minFrequency=1,maxExtend=4000,maxFrequency=8,sampleRate=1378.125)
vibRate, vibExt = vib(pitch)

**When I run this code, 'Segmentation fault: 11' occurs.**

**Comment by dbogdanov** [comment] 2017-04-03 12:33
Can you share an audio example? (Cannot reproduce with mine).

**Comment by minzwon** [comment] 2017-04-04 09:57
Dear Dmitry,

Here I share the audio example.
I checked it once again and I realized that the code works sometimes.
However, it showed 'Segmentation fault:11' in several trials.

Best,
Minz

**Comment by dbogdanov** [comment] 2017-04-10 14:42
Fixed in 8a6de236a010692836ab072e0070221f0db61e21

**Comment by dbogdanov** [comment] 2017-04-10 14:43
Try [vibrato-fix branch](https://github.com/MTG/essentia/compare/vibrato-fix).

**Closed** 2017-04-11 15:57 UTC
Labels: bug
