### ISSUE TITLE
Issues detecting and building with gaia2 within virtualenv

### ISSUE THREAD

**Issue by njhwang** [MTG/essentia#29] opened 2013-12-04 09:03 UTC
I had a heck of a time getting waf to detect and build with gaia2 within a virtualenv, so figured I'd note some of the things I had to do in case it helps anyone smarter than me make the process more seamless for future users.

After running gaia2's waf configure (with --prefix=$VIRTUAL_ENV), build, and install within my virtualenv, the first problem was that essentia's waf configure (again with --prefix=$VIRTUAL_ENV) couldn't find my gaia2 installation. I figured out that this was because pkg-config couldn't find gaia2 when it got installed to $VIRTUAL_ENV/lib/pkgconfig. The only quick way I could see to get things to work was to modify my virtualenv's activate script to update/reset the $PKG_CONFIG_PATH appropriately upon activate/deactivate. 

essentia's waf could then detect gaia2, but was running into compilation errors:

```
In file included from ../src/algorithms/essentia_algorithms_reg.cpp:117:0:
/home/njhwang/Documents/my-dev/essentia/src/algorithms/highlevel/gaiatransform.h:23:34: fatal error: gaia2/transformation.h: No such file or directory
compilation terminated.
```

The g++ invocation had the following flag to include the gaia2 headers that were installed in my virtualenv, which definitely contained transformation.h:

    -I/home/njhwang/Documents/pyenvs/sirenuse/include/gaia2

Since transformation.h was executing "#include <gaia2/transformation.h>", I thought perhaps it was looking for another gaia2 folder within the included directory mentioned above.

I modified the gaia2.pc file in my $VIRTUAL_ENV/lib/pkgconfig directory to make sure that the following got included to the g++ flags:

   -I/home/njhwang/Documents/pyenvs/sirenuse/include

I was then able to completely build and install essentia from a virtualenv.

**Comment by dbogdanov** [comment] 2015-03-20 18:21
@alastair did you have any similar issue?

**Comment by alastair** [comment] 2015-03-23 09:29
I haven't tried to install gaia to a venv and then find it with essentia
(I've installed essentia to a venv with no problem, and gaia as well to use
the model training).

I'll take a look.

**Comment by alastair** [comment] 2015-04-23 11:33
I can confirm this is a problem with gaia and taglib in non-standard locations.

The description of the problem above seems to be about right - 
pkg-config gives gaia's include directory as `-I$PREFIX/include/gaia2` then the code in essentia includes as `#include <gaia2/transformation.h>`
This appears to have always worked because gaia would by default install into `/usr/local/include/gaia2`, which would be found because it's already in `/usr/local/include`.

I think taglib will be in a similar situation, we include this as `#include <taglib/...>`, while pkg-config gives the include dir as `-I/usr/include/taglib` (for system installed taglib).

I looked at some taglib examples (https://github.com/taglib/taglib/blob/master/examples/tagreader.cpp) and they don't add the `taglib/` prefix in the include.
After I removed the prefixes it worked fine. I suggest we do the same.

**Closed** 2015-06-22 15:51 UTC
