### ISSUE TITLE
Invertible CQT transforms

### ISSUE THREAD

**Issue by nkundiushuti** [MTG/essentia#289] opened 2015-08-31 08:16 UTC
It would be nice to have one of the invertible CQT transforms implemented here:
- https://github.com/wslihgt/pyfasst/tree/master/pyfasst/tftransforms
Schoerkhuber, C. and Klapuri, A.,
   \"Constant-Q transform toolbox for music processing,\"
or 
- https://github.com/grrrr/nsgt
Also check the more recent paper which is a combination of the previous two:
http://www.cs.tut.fi/sgn/arg/CQT/schoerkhuber-aes-2014.pdf

**Comment by dbogdanov** [comment] 2015-08-31 12:43
Duplicate of #136

**Closed by dbogdanov** 2015-08-31 12:43 UTC
