### ISSUE TITLE
Segmentation fault when essentia python module imported after other module with C extensions

### ISSUE THREAD

**Issue by aagnone3** [MTG/essentia#433] opened 2016-06-21 20:46 UTC
When essentia is imported after another library with C/C++ extensions has been imported, a segmentation fault occurs.

Case 1:
>>> import essentia
>>> import numpy
Result: successful imports

Case 2:
>>> import numpy
>>> import essentia
Result: Segmentation fault (core dumped)

**Comment by alastair** [comment] 2016-07-27 15:32
Works fine for me. Can you explain your infrastructure a bit more?
 - which operating system
 - did you compile python yourself
 - did you compile numpy yourself
 - are you able to run this under gdb to get a backtrace (even if it just has shared library names, not debug info)

**Comment by dbogdanov** [comment] 2016-10-03 13:23
Closing as I could not reproduce this error (tested on Ubuntu and OSX) and more information is missing.

**Closed by dbogdanov** 2016-10-03 13:23 UTC
