### ISSUE TITLE
test failed，how can i solve it

### ISSUE THREAD

**Issue by wxy656** [MTG/essentia#419] opened 2016-06-13 08:59 UTC
[  FAILED  ] 7 tests, listed below:
[  FAILED  ] AudioLoader.SimpleLoad
[  FAILED  ] AudioLoader.SampleFormatConversion
[  FAILED  ] Network.SimpleVisibleNetwork
[  FAILED  ] Network.ExecutionNetworkWithComposite
[  FAILED  ] Scheduler.SourceProxyFork
[  FAILED  ] TreeTraversal.DepthFirstMap
[  FAILED  ] TreeTraversal.DepthFirstSearch

**Comment by alastair** [comment] 2016-06-13 09:18
Duplicate of #413

**Closed by alastair** 2016-06-13 09:18 UTC
