### ISSUE TITLE
Trouble installing gaia

### ISSUE THREAD

**Issue by danieleghisi** [MTG/essentia#412] opened 2016-05-29 13:58 UTC
I'm having troubles instaling gaia via the brew formula on Mac OS.
The error is "Could not load the Waf tool".
Here's the full terminal output.
Does anyone know a workaround?
Thanks,
Daniele

MacBook-Pro-di-Daniele-2:gaia-2.4.4 danieleghisi$ brew install gaia --HEAD
==> Installing gaia from mtg/essentia
==> Cloning https://github.com/MTG/gaia.git
Updating /Library/Caches/Homebrew/gaia--git
==> Checking out branch master
==> ./waf configure --download --with-python-bindings --prefix=/usr/local/Cellar/gaia/HEAD
Last 15 lines from /Users/danieleghisi/Library/Logs/Homebrew/gaia/01.waf:
Checking for 'QtGui'                     : yes 
Checking for 'QtUiTools'                 : yes 
Checking for 'QtNetwork'                 : yes 
Checking for 'QtOpenGL'                  : yes 
Checking for 'QtSql'                     : yes 
Checking for 'QtSvg'                     : yes 
Checking for 'QtTest'                    : yes 
Checking for 'QtXml'                     : yes 
Checking for 'QtXmlPatterns'             : yes 
Checking for 'QtWebKit'                  : yes 
Checking for 'Qt3Support'                : not found 
Checking for 'QtHelp'                    : yes 
Checking for 'QtScript'                  : yes 
Checking for 'QtDeclarative'             : yes 
Could not load the Waf tool

**Comment by dbogdanov** [comment] 2016-05-30 10:08
Closing is this is a duplicate of [#29](https://github.com/MTG/gaia/issues/29)

**Closed by dbogdanov** 2016-05-30 10:08 UTC
