### ISSUE TITLE
what is the frequency grid of pfft?

### ISSUE THREAD

**Issue by great-thoughts** [MTG/essentia#425] opened 2016-06-16 06:59 UTC
When I compute fft of my signal of length s, the fft has length s/2+1. what is the frequency grid? I was expecting that fft will have s/2+1 length and it will only provide me with the spectrum of the positive frequencies. however, it gives me the spectrum of both positive and negative frequencies.

**Comment by dbogdanov** [comment] 2016-06-16 12:34
Duplicate of #240

**Closed by dbogdanov** 2016-06-16 12:34 UTC
