### ISSUE TITLE
Implement python bindings on Windows

### ISSUE THREAD

**Issue by shreyavaidy** [MTG/essentia#439] opened 2016-07-10 07:14 UTC
Hello,
Im new to this and I wanted to use essentia with python on my windows system. I tried to cross-compile using the steps provided but Im totallly lost. I installed mingw32 on ubuntu and followed the three steps given and didnt know what to do further.
It would of great help if someone could run me through the steps and how to finally achieve "import essentia.standard" on my windows 8. Sorry if its a very amateur question, but I'm in grave need of help right now and have only this module left in my application.
Thank you!

**Comment by dbogdanov** [comment] 2016-07-18 16:36
Python for windows is not supported yet, only C++.

**Comment by shreyavaidy** [comment] 2016-07-18 17:23
Yes, I figured that out a few days later. Thanks anyway.

**Comment by alastair** [comment] 2016-07-25 15:05
Duplicate of https://github.com/MTG/essentia/issues/243

**Closed by alastair** 2016-07-25 15:05 UTC
