### ISSUE TITLE
Some python unit tests fail on first round

### ISSUE THREAD

**Issue by edufonseca** [MTG/essentia#498] opened 2016-11-04 19:55 UTC
In the 1st round of unit tests, the following errors/fails occur on Ubuntu 15.10:

```
======================================================================
ERROR: testImpulse (rhythm.test_onsetdetection.TestOnsetDetection)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edfm/upf/essentia/test/src/unittest/rhythm/test_onsetdetection.py", line 98, in testImpulse
    self.assertEqual(onset_melflux(mag,ph), 0)
  File "/home/edfm/upf/essentia/build/python/essentia/standard.py", line 100, in __call__
    return self.compute(*args)
  File "/home/edfm/upf/essentia/build/python/essentia/standard.py", line 85, in compute
    results = self.__compute__(*convertedArgs)
RuntimeError: In OnsetDetection.compute: MelBands: the number of spectrum bins is insufficient for the specified number of mel bands. Use zero padding to increase the number of FFT bins.

======================================================================
ERROR: testZero (spectral.test_mfcc.TestMFCC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edfm/upf/essentia/test/src/unittest/spectral/test_mfcc.py", line 53, in testZero
    bands, mfcc = MFCC()(zeros(size))
  File "/home/edfm/upf/essentia/build/python/essentia/standard.py", line 100, in __call__
    return self.compute(*args)
  File "/home/edfm/upf/essentia/build/python/essentia/standard.py", line 85, in compute
    results = self.__compute__(*convertedArgs)
RuntimeError: In MFCC.compute: MelBands: the number of spectrum bins is insufficient for the specified number of mel bands. Use zero padding to increase the number of FFT bins.

======================================================================
FAIL: testImpulseTrain (rhythm.test_rhythmextractor.TestRhythmExtractor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edfm/upf/essentia/test/src/unittest/rhythm/test_rhythmextractor.py", line 288, in testImpulseTrain
    self.assertVectorWithinVectorFixedPrecision(result[1], expectedTicks, 1)
  File "/home/edfm/upf/essentia/test/src/unittest/rhythm/test_rhythmextractor.py", line 119, in assertVectorWithinVectorFixedPrecision
    self.assertAlmostEqualFixedPrecision(found[i], expected[j-1], precision)
  File "/home/edfm/upf/essentia/test/src/unittest/essentia_test.py", line 102, in assertAlmostEqualFixedPrecision
    BaseTestCase.assertAlmostEqual(self, found, expected, digits)
AssertionError: 10.369769 != 10.0 within 1 places

======================================================================
FAIL: testImpulse (rhythm.test_superfluxextractor.TestSuperFluxExtractor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edfm/upf/essentia/test/src/unittest/rhythm/test_superfluxextractor.py", line 48, in testImpulse
    self.assertAlmostEqualVectorAbs(result, expected, 256./44100)
  File "/home/edfm/upf/essentia/test/src/unittest/essentia_test.py", line 159, in assertAlmostEqualVectorAbs
    self.assertAlmostEqualAbs(val1, val2, precision)
  File "/home/edfm/upf/essentia/test/src/unittest/essentia_test.py", line 154, in assertAlmostEqualAbs
    self.assert_(diff <= precision, 'Difference is %e while allowed absolute error is %e' % (diff, precision))
AssertionError: Difference is 2.979591e-02 while allowed absolute error is 5.804989e-03

======================================================================
FAIL: testARealCase (tonal.test_pitchyinfft.TestPitchYinFFT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edfm/upf/essentia/test/src/unittest/tonal/test_pitchyinfft.py", line 131, in testARealCase
    self.assertAlmostEqualVector(pitch, expected_pitch)
  File "/home/edfm/upf/essentia/test/src/unittest/essentia_test.py", line 129, in assertAlmostEqualVector
    self.assertAlmostEqual(val1, val2, precision)
  File "/home/edfm/upf/essentia/test/src/unittest/essentia_test.py", line 116, in assertAlmostEqual
    self.assert_(diff <= precision, 'Difference is %e while allowed deviation from the expected value is %e %%' % (diff, precision*100))
AssertionError: Difference is 1.141042e-02 while allowed deviation from the expected value is 1.000000e-05 %

======================================================================
FAIL: testBrownNoise (highlevel.test_danceability.TestDanceability)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edfm/upf/essentia/test/src/unittest/highlevel/test_danceability.py", line 109, in testBrownNoise
    self.assertAlmostEqualVectorAbs(dfa, [1.5] * 35, 0.1)
  File "/home/edfm/upf/essentia/test/src/unittest/essentia_test.py", line 159, in assertAlmostEqualVectorAbs
    self.assertAlmostEqualAbs(val1, val2, precision)
  File "/home/edfm/upf/essentia/test/src/unittest/essentia_test.py", line 154, in assertAlmostEqualAbs
    self.assert_(diff <= precision, 'Difference is %e while allowed absolute error is %e' % (diff, precision))
AssertionError: Difference is 9.385940e-01 while allowed absolute error is 1.000000e-01

======================================================================
FAIL: testPinkNoise (highlevel.test_danceability.TestDanceability)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edfm/upf/essentia/test/src/unittest/highlevel/test_danceability.py", line 100, in testPinkNoise
    self.assertAlmostEqualVectorAbs(dfa, [1.0] * 35, 0.1)
  File "/home/edfm/upf/essentia/test/src/unittest/essentia_test.py", line 159, in assertAlmostEqualVectorAbs
    self.assertAlmostEqualAbs(val1, val2, precision)
  File "/home/edfm/upf/essentia/test/src/unittest/essentia_test.py", line 154, in assertAlmostEqualAbs
    self.assert_(diff <= precision, 'Difference is %e while allowed absolute error is %e' % (diff, precision))
AssertionError: Difference is 4.500718e-01 while allowed absolute error is 1.000000e-01

======================================================================
FAIL: testRealCase (spectral.test_mfcc.TestMFCC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edfm/upf/essentia/test/src/unittest/spectral/test_mfcc.py", line 97, in testRealCase
    self.assertAlmostEqualVector(mean(pool['mfcc'], 0), expected, 1.0e-5)
  File "/home/edfm/upf/essentia/test/src/unittest/essentia_test.py", line 129, in assertAlmostEqualVector
    self.assertAlmostEqual(val1, val2, precision)
  File "/home/edfm/upf/essentia/test/src/unittest/essentia_test.py", line 116, in assertAlmostEqual
    self.assert_(diff <= precision, 'Difference is %e while allowed deviation from the expected value is %e %%' % (diff, precision*100))
AssertionError: Difference is 1.266321e-05 while allowed deviation from the expected value is 1.000000e-03 %

======================================================================
FAIL: testOgg (io.test_audiowriter_streaming.TestAudioWriter_Streaming)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edfm/upf/essentia/test/src/unittest/io/test_audiowriter_streaming.py", line 223, in testOgg
    self.encoderTest('audiowritertest.ogg', precision=5e-6);
  File "/home/edfm/upf/essentia/test/src/unittest/io/test_audiowriter_streaming.py", line 197, in encoderTest
    self.assertAlmostEqual(max(pool['audio']), max(sine), precision)
  File "/home/edfm/upf/essentia/test/src/unittest/essentia_test.py", line 116, in assertAlmostEqual
    self.assert_(diff <= precision, 'Difference is %e while allowed deviation from the expected value is %e %%' % (diff, precision*100))
AssertionError: Difference is 1.044999e-02 while allowed deviation from the expected value is 5.000000e-04 %

======================================================================
FAIL: testRegression (io.test_audiowriter_streaming.TestAudioWriter_Streaming)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edfm/upf/essentia/test/src/unittest/io/test_audiowriter_streaming.py", line 69, in testRegression
    self.compare(pool['audio'], signal)
  File "/home/edfm/upf/essentia/test/src/unittest/io/test_audiowriter_streaming.py", line 34, in compare
    self.assertAlmostEqual(result[i][1] - expected[i][1], 0, 0.5/32767)
  File "/home/edfm/upf/essentia/test/src/unittest/essentia_test.py", line 116, in assertAlmostEqual
    self.assert_(diff <= precision, 'Difference is %e while allowed deviation from the expected value is %e %%' % (diff, precision*100))
AssertionError: Difference is 3.051758e-05 while allowed deviation from the expected value is 1.525925e-03 %

======================================================================
FAIL: testSaturation (io.test_audiowriter_streaming.TestAudioWriter_Streaming)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edfm/upf/essentia/test/src/unittest/io/test_audiowriter_streaming.py", line 140, in testSaturation
    self.compare(pool['audio'], expected)
  File "/home/edfm/upf/essentia/test/src/unittest/io/test_audiowriter_streaming.py", line 33, in compare
    self.assertAlmostEqual(result[i][0] - expected[i][0], 0, 0.5/32767)
  File "/home/edfm/upf/essentia/test/src/unittest/essentia_test.py", line 116, in assertAlmostEqual
    self.assert_(diff <= precision, 'Difference is %e while allowed deviation from the expected value is %e %%' % (diff, precision*100))
AssertionError: Difference is 3.051758e-05 while allowed deviation from the expected value is 1.525925e-03 %

======================================================================
FAIL: testMD5 (io.test_audioloader_streaming.TestAudioLoader_Streaming)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edfm/upf/essentia/test/src/unittest/io/test_audioloader_streaming.py", line 241, in testMD5
    self.assertEqual(md5_ogg, "a87dad40fea0966cc5b967d5412e8868")
AssertionError: 'd90386f75405eb12c7555d2ea8fd0f16' != 'a87dad40fea0966cc5b967d5412e8868'

----------------------------------------------------------------------
Ran 1074 tests in 267.247s

FAILED (failures=10, errors=2)
```

**Comment by dbogdanov** [comment] 2016-11-07 13:55
Duplicate of #316

**Closed by dbogdanov** 2016-11-07 13:55 UTC
