### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by srviest** [MTG/essentia#413] opened 2016-05-29 16:41 UTC
Same problem in #72 happened to me, when I try to run the c++ base unit tests there are 7 errors
but I am using the 2.1 beta
[ FAILED ] AudioLoader.SimpleLoad
[ FAILED ] AudioLoader.SampleFormatConversion
[ FAILED ] Network.SimpleVisibleNetwork
[ FAILED ] Network.ExecutionNetworkWithComposite
[ FAILED ] Scheduler.SourceProxyFork
[ FAILED ] TreeTraversal.DepthFirstMap
[ FAILED ] TreeTraversal.DepthFirstSearch

**Comment by dbogdanov** [comment] 2016-05-30 09:50
Try using master branch.

**Comment by wxy656** [comment] 2016-06-13 10:36
when i try master branch .the failed tests' number  become to 11,and several of the are the same

[  FAILED  ] 11 tests, listed below:
[  FAILED  ] AudioLoader.SimpleLoad
[  FAILED  ] AudioLoader.SampleFormatConversion
[  FAILED  ] Network.SimpleVisibleNetwork
[  FAILED  ] Network.SimpleExecutionNetwork
[  FAILED  ] Network.ExecutionNetworkWithComposite
[  FAILED  ] Network.ExecutionNetworkKeyExtractor
[  FAILED  ] Network.ExecutionNetworkKeyExtractorConnected
[  FAILED  ] NetworkParser.ConnectionsAndInstantiation
[  FAILED  ] Scheduler.SourceProxyFork
[  FAILED  ] TreeTraversal.DepthFirstMap
[  FAILED  ] TreeTraversal.DepthFirstSearch

**Comment by wxy656** [comment] 2016-06-13 10:57
I think maybe something is wrong on configure :

- fftw detected!
- FFmpeg (or LibAv on debian/ubuntu) seems to be missing.
  The following algorithms will be ignored: ['AudioLoader', 'MonoLoader', 'EqloudLoader', 'EasyLoader', 'MonoWriter', 'AudioWriter']

but i have installed  ffmpeg on my device ,i dont' know why says "seems to be missing" :
ffmpeg,ffmpeg version 2.4.11 Copyright (c) 2000-2015 the FFmpeg developers

**Comment by dbogdanov** [comment] 2016-06-13 14:41
You can see the details in ```build/config.log```. See the output for libavcodec,  libavformat and libavutil.

**Comment by alastair** [comment] 2016-07-25 14:29
Root cause seems to be missing ffmpeg. Closing, but we can track actual test failures in https://github.com/MTG/essentia/issues/316

**Closed by alastair** 2016-07-25 14:29 UTC

**Comment by shivachaitanya** [comment] 2017-07-16 05:00
I am also facing same issue, ffmpeg is present, but still the problem persists, can you give suggestion ?

**Comment by Aishwarya-96** [comment] 2019-03-26 16:34
I have the same issue. I have ffmpeg version 3.4.4 and I am using Ubuntu 18.
