### ISSUE TITLE
Install via homebrew --HEAD --with-gaia fails due to missing swig 

### ISSUE THREAD

**Issue by vade** [MTG/essentia#632] opened 2017-08-04 15:55 UTC
Likely user / configuration error but installing essentia via instructions for homebrew with gaia fails:

Im likely missing something easy and the issue is on my end, but on Mac OS X 10.12.6 with system python, running home-brew / following the install instructions I get : 

swig:

```
Andromeda:~ vade$ which swig
/usr/local/bin/swig
```

install: 

```
Andromeda:~ vade$ brew install essentia --HEAD --with-gaia 
==> Installing essentia from mtg/essentia
==> Installing dependencies for mtg/essentia/essentia: gaia
==> Installing mtg/essentia/essentia dependency: gaia
==> Using the sandbox
==> Downloading https://github.com/MTG/gaia/archive/v2.4.4.tar.gz
Already downloaded: /Users/vade/Library/Caches/Homebrew/gaia-2.4.4.tar.gz
==> ./waf configure --with-python-bindings --prefix=/usr/local/Cellar/gaia/2.4.4
Last 15 lines from /Users/vade/Library/Logs/Homebrew/gaia/01.waf:
Checking for 'QtNetwork'                 : yes 
Checking for 'QtOpenGL'                  : yes 
Checking for 'QtSql'                     : yes 
Checking for 'QtSvg'                     : yes 
Checking for 'QtTest'                    : yes 
Checking for 'QtXml'                     : yes 
Checking for 'QtXmlPatterns'             : yes 
Checking for 'QtWebKit'                  : not found 
Checking for 'Qt3Support'                : yes 
Checking for 'QtHelp'                    : yes 
Checking for 'QtScript'                  : yes 
Checking for 'QtDeclarative'             : yes 
Could not load the Waf tool 'swig' from ['/private/tmp/gaia-20170804-82706-t4im9w/gaia-2.4.4/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c', '/private/tmp/gaia-20170804-82706-t4im9w/gaia-2.4.4/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib', '/private/tmp/gaia-20170804-82706-t4im9w/gaia-2.4.4', '/Library/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/six-1.10.0-py2.7.egg', '/Library/Python/2.7/site-packages/numpy-1.11.2-py2.7-macosx-10.12-intel.egg', '/Library/Python/2.7/site-packages/wheel-0.30.0a0-py2.7.egg', '/usr/local/lib/python2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/private/tmp/gaia-20170804-82706-t4im9w/gaia-2.4.4/.brew_home/Library/Python/2.7/lib/python/site-packages', '/usr/local/lib/python2.7/site-packages', '/Library/Python/2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC'] (try the --download option?):
No module named swig
(complete log in /private/tmp/gaia-20170804-82706-t4im9w/gaia-2.4.4/build/config.log)

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/mtg/homebrew-essentia/issues
```

System python also cant see swig so I'm sure I'm messing something up :)

```
Andromeda:~ vade$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import swig
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named swig
```

Thank you

**Comment by bartvdbraak** [comment] 2018-06-13 20:39
Same problem

**Comment by umezo** [comment] 2018-09-17 03:34
I had the same problem and it was resolved by set PYTHON_PATH into the environment variables

https://github.com/MTG/essentia/issues/113#issuecomment-49461111

**Comment by fn2189** [comment] 2018-12-18 22:37
Also, when I try to install gaia separtely through

```brew install gaia --HEAD```
and then run 
```brew install essentia --HEAD --with-gaia```, 
I am faced with the following issue:
```2018-12-18 14:36:54 -0500

./waf

Waf: Entering directory `/private/tmp/essentia-20181218-49430-1s465aq/build'
→ building from /private/tmp/essentia-20181218-49430-1s465aq
→ building from /private/tmp/essentia-20181218-49430-1s465aq/src
Building all the algorithms
Ignoring the following algorithms: IFFTA, IFFTK, FFTA, FFTK
Created algorithms registration file
→ building from /private/tmp/essentia-20181218-49430-1s465aq/src/examples
[  1/266] Compiling src/algorithms/spectral/mfcc.cpp
[  2/266] Compiling src/algorithms/extractor/musicextractorsvm.cpp
[  3/266] Compiling src/algorithms/io/monowriter.cpp
[  4/266] Compiling src/essentia/utils/extractor_music/MusicLowlevelDescriptors.cpp
[  5/266] Compiling src/essentia/streaming/algorithms/ringbufferinput.cpp
[  6/266] Compiling src/essentia/parameter.cpp
[  7/266] Compiling src/essentia/connector.cpp
[  8/266] Compiling src/essentia/algorithm.cpp
[  9/266] Compiling src/algorithms/tonal/pitchyin.cpp
[ 10/266] Compiling src/algorithms/standard/nsgconstantqstreaming.cpp
[ 11/266] Compiling src/algorithms/standard/cubicspline.cpp
[ 12/266] Compiling src/algorithms/experimental/meter.cpp
[ 13/266] Compiling src/algorithms/filters/bandreject.cpp
[ 14/266] Compiling src/algorithms/rhythm/singlebeatloudness.cpp
[ 15/266] Compiling src/algorithms/stats/entropy.cpp
[ 16/266] Compiling src/essentia/utils/extractor_freesound/FreesoundRhythmDescriptors.cpp
[ 17/266] Compiling src/algorithms/sfx/pitchsalience.cpp
[ 18/266] Compiling src/algorithms/standard/startstopsilence.cpp
[ 19/266] Compiling src/algorithms/sfx/tctototal.cpp
[ 20/266] Compiling src/algorithms/standard/stereodemuxer.cpp
[ 21/266] Compiling src/algorithms/standard/silencerate.cpp
[ 22/266] Compiling src/algorithms/highlevel/pca.cpp
[ 23/266] Compiling src/algorithms/standard/envelope.cpp
[ 24/266] Compiling src/essentia/essentiautil.cpp
[ 25/266] Compiling src/algorithms/rhythm/superfluxpeaks.cpp
[ 26/266] Compiling src/algorithms/spectral/panning.cpp
[ 27/266] Compiling src/algorithms/filters/iir.cpp
[ 28/266] Compiling src/algorithms/spectral/triangularbarkbands.cpp
[ 29/266] Compiling src/algorithms/rhythm/loopbpmestimator.cpp
[ 30/266] Compiling src/algorithms/temporal/effectiveduration.cpp
[ 31/266] Compiling src/algorithms/rhythm/bpmrubato.cpp
[ 32/266] Compiling src/essentia/utils/audiocontext.cpp
[ 33/266] Compiling src/algorithms/spectral/rolloff.cpp
[ 34/266] Compiling src/algorithms/tonal/tristimulus.cpp
[ 35/266] Compiling src/algorithms/synthesis/sprmodelsynth.cpp
[ 36/266] Compiling src/algorithms/spectral/spectrumtocent.cpp
[ 37/266] Compiling src/algorithms/temporal/zerocrossingrate.cpp
[ 38/266] Compiling src/algorithms/filters/highpass.cpp
[ 39/266] Compiling src/algorithms/rhythm/loopbpmconfidence.cpp
[ 40/266] Compiling src/essentia/streaming/accumulatoralgorithm.cpp
[ 41/266] Compiling src/algorithms/tonal/highresolutionfeatures.cpp
[ 42/266] Compiling src/algorithms/highlevel/chromaprinter.cpp
[ 43/266] Compiling src/algorithms/standard/binaryoperatorstream.cpp
[ 44/266] Compiling src/algorithms/synthesis/hprmodelanal.cpp
[ 45/266] Compiling src/algorithms/rhythm/superfluxnovelty.cpp
[ 46/266] Compiling src/algorithms/extractor/lowlevelspectralextractor.cpp
[ 47/266] Compiling src/algorithms/tonal/dissonance.cpp
[ 48/266] Compiling src/essentia/utils/asciidag.cpp
[ 49/266] Compiling src/algorithms/standard/peakdetection.cpp
[ 50/266] Compiling src/algorithms/standard/vectorrealaccumulator.cpp
[ 51/266] Compiling src/algorithms/synthesis/harmonicmodelanal.cpp
[ 52/266] Compiling src/algorithms/standard/maxfilter.cpp
[ 53/266] Compiling src/algorithms/synthesis/sprmodelanal.cpp
[ 54/266] Compiling src/algorithms/standard/stereotrimmer.cpp
[ 55/266] Compiling src/algorithms/extractor/levelextractor.cpp
[ 56/266] Compiling src/essentia/configurable.cpp
[ 57/266] Compiling src/algorithms/stats/centralmoments.cpp
[ 58/266] Compiling src/algorithms/synthesis/sinesubtraction.cpp
[ 59/266] Compiling src/algorithms/tonal/tonicindianartmusic.cpp
[ 60/266] Compiling src/algorithms/tonal/harmonicpeaks.cpp
[ 61/266] Compiling src/algorithms/stats/distributionshape.cpp
[ 62/266] Compiling src/algorithms/standard/stereomuxer.cpp
[ 63/266] Compiling src/algorithms/filters/movingaverage.cpp
[ 64/266] Compiling src/essentia/streaming/streamingalgorithmwrapper.cpp
[ 65/266] Compiling src/algorithms/tonal/chordsdetectionbeats.cpp
[ 66/266] Compiling src/algorithms/highlevel/intensity.cpp
[ 67/266] Compiling src/algorithms/tonal/pitchcontoursegmentation.cpp
[ 68/266] Compiling src/algorithms/io/audiowriter.cpp
[ 69/266] Compiling src/algorithms/standard/framecutter.cpp
[ 70/266] Compiling src/algorithms/spectral/spectralcontrast.cpp
[ 71/266] Compiling src/algorithms/rhythm/onsets.cpp
[ 72/266] Compiling src/essentia/scheduler/network.cpp
[ 73/266] Compiling src/algorithms/rhythm/rhythmextractor.cpp
[ 74/266] Compiling src/algorithms/rhythm/superfluxextractor.cpp
[ 75/266] Compiling src/algorithms/standard/windowing.cpp
[ 76/266] Compiling src/algorithms/spectral/hpcp.cpp
[ 77/266] Compiling src/algorithms/standard/bpf.cpp
[ 78/266] Compiling src/algorithms/tonal/oddtoevenharmonicenergyratio.cpp
[ 79/266] Compiling src/algorithms/rhythm/percivalenhanceharmonics.cpp
[ 80/266] Compiling src/essentia/streaming/streamingalgorithm.cpp
[ 81/266] Compiling src/algorithms/rhythm/percivalevaluatepulsetrains.cpp
[ 82/266] Compiling src/algorithms/stats/variance.cpp
[ 83/266] Compiling src/algorithms/tonal/tuningfrequency.cpp
[ 84/266] Compiling src/algorithms/extractor/rhythmdescriptors.cpp
[ 85/266] Compiling src/algorithms/rhythm/harmonicbpm.cpp
[ 86/266] Compiling src/algorithms/tonal/chordsdescriptors.cpp
[ 87/266] Compiling src/algorithms/io/easyloader.cpp
[ 88/266] Compiling src/essentia/debugging.cpp
[ 89/266] Compiling src/algorithms/rhythm/percivalbpmestimator.cpp
[ 90/266] Compiling src/algorithms/spectral/barkbands.cpp
[ 91/266] Compiling src/algorithms/tonal/multipitchmelodia.cpp
[ 92/266] Compiling src/algorithms/rhythm/rhythmextractor2013.cpp
[ 93/266] Compiling src/algorithms/tonal/pitchmelodia.cpp
[ 94/266] Compiling src/algorithms/tonal/pitchcontoursmultimelody.cpp
[ 95/266] Compiling src/algorithms/standard/noiseadder.cpp
[ 96/266] Compiling src/essentia/streaming/sinkbase.cpp
[ 97/266] Compiling src/algorithms/filters/lowpass.cpp
[ 98/266] Compiling src/algorithms/rhythm/beatsloudness.cpp
[ 99/266] Compiling src/algorithms/tonal/pitchcontoursmonomelody.cpp
[100/266] Compiling src/essentia/utils/yamlast.cpp
[101/266] Compiling src/algorithms/rhythm/bpmhistogram.cpp
[102/266] Compiling src/algorithms/complex/polartocartesian.cpp
[103/266] Compiling src/algorithms/stats/flatness.cpp
[104/266] Compiling src/essentia/pool.cpp
[105/266] Compiling src/algorithms/io/audioonsetsmarker.cpp
[106/266] Compiling src/algorithms/stats/geometricmean.cpp
[107/266] Compiling src/algorithms/standard/nsgconstantq.cpp
[108/266] Compiling src/essentia/utils/jsonconvert.cpp
[109/266] Compiling src/algorithms/filters/dcremoval.cpp
[110/266] Compiling src/algorithms/tonal/predominantpitchmelodia.cpp
[111/266] Compiling src/algorithms/rhythm/onsetdetectionglobal.cpp
[112/266] Compiling src/essentia/streaming/algorithms/ringbufferoutput.cpp
[113/266] Compiling src/algorithms/spectral/gfcc.cpp
[114/266] Compiling src/algorithms/stats/energy.cpp
[115/266] Compiling src/3rdparty/spline/splineutil.cpp
[116/266] Compiling src/algorithms/standard/autocorrelation.cpp
[117/266] Compiling src/algorithms/spectral/triangularbands.cpp
[118/266] Compiling src/algorithms/standard/warpedautocorrelation.cpp
[119/266] Compiling src/algorithms/tonal/pitchyinfft.cpp
[120/266] Compiling src/algorithms/standard/unaryoperatorstream.cpp
[121/266] Compiling src/algorithms/extractor/extractor.cpp
[122/266] Compiling src/algorithms/filters/equalloudness.cpp
[123/266] Compiling src/algorithms/extractor/tuningfrequencyextractor.cpp
[124/266] Compiling src/algorithms/synthesis/sinemodelsynth.cpp
[125/266] Compiling src/algorithms/tonal/key.cpp
[126/266] Compiling src/algorithms/standard/crosscorrelation.cpp
[127/266] Compiling src/essentia/utils/extractor_freesound/FreesoundSfxDescriptors.cpp
[128/266] Compiling src/algorithms/stats/median.cpp
[129/266] Compiling src/algorithms/filters/allpass.cpp
[130/266] Compiling src/algorithms/rhythm/rhythmtransform.cpp
[131/266] Compiling src/algorithms/tonal/inharmonicity.cpp
[132/266] Compiling src/algorithms/synthesis/stochasticmodelsynth.cpp
[133/266] Compiling src/algorithms/standard/constantq.cpp
[134/266] Compiling src/algorithms/synthesis/sinemodelanal.cpp
[135/266] Compiling src/essentia/streaming/algorithms/devnull.cpp
[136/266] Compiling src/algorithms/standard/resample.cpp
[137/266] Compiling src/algorithms/standard/chromagram.cpp
[138/266] Compiling src/algorithms/sfx/aftermaxtobeforemaxenergyratio.cpp
[139/266] Compiling src/algorithms/temporal/loudness.cpp
[140/266] Compiling src/algorithms/rhythm/beattrackermultifeature.cpp
[141/266] Compiling src/algorithms/standard/overlapadd.cpp
[142/266] Compiling src/algorithms/complex/cartesiantopolar.cpp
[143/266] Compiling src/essentia/utils/asciidagparser.cpp
[144/266] Compiling src/algorithms/io/audioloader.cpp
[145/266] Compiling src/algorithms/standard/idct.cpp
[146/266] Compiling src/algorithms/synthesis/stochasticmodelanal.cpp
[147/266] Compiling src/algorithms/spectral/strongpeak.cpp
[148/266] Compiling src/algorithms/stats/decrease.cpp
[149/266] Compiling src/algorithms/standard/scale.cpp
[150/266] Compiling src/algorithms/temporal/duration.cpp
[151/266] Compiling src/essentia/essentia.cpp
[152/266] Compiling src/algorithms/highlevel/gaiatransform.cpp
[153/266] Compiling src/algorithms/stats/centroid.cpp
[154/266] Compiling src/algorithms/io/yamlinput.cpp
[155/266] Compiling src/algorithms/sfx/maxtototal.cpp
[156/266] Compiling src/algorithms/spectral/energyband.cpp
[157/266] Compiling src/algorithms/highlevel/sbic.cpp
[158/266] Compiling src/algorithms/filters/bandpass.cpp
[159/266] Compiling src/essentia/streaming/streamingalgorithmcomposite.cpp
[160/266] Compiling src/algorithms/tonal/pitchsaliencefunction.cpp
In file included from ../src/algorithms/highlevel/gaiatransform.cpp:20:
In file included from ../src/algorithms/highlevel/gaiatransform.h:23:
In file included from /usr/local/Cellar/gaia/HEAD-95f4851/include/gaia2/transformation.h:25:
In file included from /usr/local/Cellar/gaia/HEAD-95f4851/include/gaia2/parameter.h:24:
In file included from /usr/local/Cellar/gaia/HEAD-95f4851/include/gaia2/types.h:26:
In file included from /usr/local/Cellar/gaia/HEAD-95f4851/include/gaia2/Eigen/Dense:2:
In file included from /usr/local/Cellar/gaia/HEAD-95f4851/include/gaia2/Eigen/LU:30:
/usr/local/Cellar/gaia/HEAD-95f4851/include/gaia2/Eigen/src/LU/arch/Inverse_SSE.h:58:60: error: constant expression evaluates to 2147483648 which cannot be narrowed to type 'int' [-Wc++11-narrowing]
    EIGEN_ALIGN16 const  int _Sign_PNNP[4] = { 0x00000000, 0x80000000, 0x80000000, 0x00000000 };
                                                           ^~~~~~~~~~
/usr/local/Cellar/gaia/HEAD-95f4851/include/gaia2/Eigen/src/LU/arch/Inverse_SSE.h:58:60: note: insert an explicit cast to silence this issue
    EIGEN_ALIGN16 const  int _Sign_PNNP[4] = { 0x00000000, 0x80000000, 0x80000000, 0x00000000 };
                                                           ^~~~~~~~~~
                                                           static_cast<int>( )
/usr/local/Cellar/gaia/HEAD-95f4851/include/gaia2/Eigen/src/LU/arch/Inverse_SSE.h:58:72: error: constant expression evaluates to 2147483648 which cannot be narrowed to type 'int' [-Wc++11-narrowing]
    EIGEN_ALIGN16 const  int _Sign_PNNP[4] = { 0x00000000, 0x80000000, 0x80000000, 0x00000000 };
                                                                       ^~~~~~~~~~
/usr/local/Cellar/gaia/HEAD-95f4851/include/gaia2/Eigen/src/LU/arch/Inverse_SSE.h:58:72: note: insert an explicit cast to silence this issue
    EIGEN_ALIGN16 const  int _Sign_PNNP[4] = { 0x00000000, 0x80000000, 0x80000000, 0x00000000 };
                                                                       ^~~~~~~~~~
                                                                       static_cast<int>( )
/usr/local/Cellar/gaia/HEAD-95f4851/include/gaia2/Eigen/src/LU/arch/Inverse_SSE.h:185:55: error: constant expression evaluates to 9223372036854775808 which cannot be narrowed to type 'long long' [-Wc++11-narrowing]
    const EIGEN_ALIGN16 long long int _Sign_NP[2] = { 0x8000000000000000ll, 0x0000000000000000ll };
                                                      ^~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/gaia/HEAD-95f4851/include/gaia2/Eigen/src/LU/arch/Inverse_SSE.h:185:55: note: insert an explicit cast to silence this issue
    const EIGEN_ALIGN16 long long int _Sign_NP[2] = { 0x8000000000000000ll, 0x0000000000000000ll };
                                                      ^~~~~~~~~~~~~~~~~~~~
                                                      static_cast<long long>( )
/usr/local/Cellar/gaia/HEAD-95f4851/include/gaia2/Eigen/src/LU/arch/Inverse_SSE.h:186:77: error: constant expression evaluates to 9223372036854775808 which cannot be narrowed to type 'long long' [-Wc++11-narrowing]
    const EIGEN_ALIGN16 long long int _Sign_PN[2] = { 0x0000000000000000ll, 0x8000000000000000ll };
                                                                            ^~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/gaia/HEAD-95f4851/include/gaia2/Eigen/src/LU/arch/Inverse_SSE.h:186:77: note: insert an explicit cast to silence this issue
    const EIGEN_ALIGN16 long long int _Sign_PN[2] = { 0x0000000000000000ll, 0x8000000000000000ll };
                                                                            ^~~~~~~~~~~~~~~~~~~~
                                                                            static_cast<long long>( )
4 errors generated.

Waf: Leaving directory `/private/tmp/essentia-20181218-49430-1s465aq/build'
Build failed
 -> task in 'essentia' failed with exit status 1 (run with -v to display more information)

HOMEBREW_VERSION: 1.8.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 858c5e1afb0eb00079a4f014e8fbedf9065d50e4
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 24e0c2fce4f2226c77ffb7b7c7d8764200556c58
Core tap last commit: 65 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /Users/franck/Library/Caches/Homebrew
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/openssl:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local/opt/openblas:/usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python/Frameworks:/usr/local/opt/qt@4/Frameworks:/usr/local/opt/python@2/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/libyaml/lib/pkgconfig:/usr/local/opt/isl/lib/pkgconfig:/usr/local/opt/mpfr/lib/pkgconfig:/usr/local/opt/fftw/lib/pkgconfig:/usr/local/opt/libogg/lib/pkgconfig:/usr/local/opt/libvorbis/lib/pkgconfig:/usr/local/opt/libvpx/lib/pkgconfig:/usr/local/opt/opus/lib/pkgconfig:/usr/local/opt/sdl2/lib/pkgconfig:/usr/local/opt/theora/lib/pkgconfig:/usr/local/opt/x264/lib/pkgconfig:/usr/local/opt/x265/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/ffmpeg/lib/pkgconfig:/usr/local/opt/libsamplerate/lib/pkgconfig:/usr/local/opt/taglib/lib/pkgconfig:/usr/local/opt/chromaprint/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/python/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/qt@4/lib/pkgconfig:/usr/local/opt/gaia/lib/pkgconfig:/usr/local/opt/python@2/lib/pkgconfig:/usr/local/opt/openblas/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/pkg-config/bin:/usr/local/opt/gcc/bin:/usr/local/opt/fftw/bin:/usr/local/opt/lame/bin:/usr/local/opt/sdl2/bin:/usr/local/opt/x264/bin:/usr/local/opt/x265/bin:/usr/local/opt/xz/bin:/usr/local/opt/ffmpeg/bin:/usr/local/opt/taglib/bin:/usr/local/opt/gdbm/bin:/usr/local/opt/openssl/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/python/bin:/usr/local/opt/pcre/bin:/usr/local/opt/swig/bin:/usr/local/opt/qt@4/bin:/usr/local/opt/gaia/bin:/usr/local/opt/python@2/bin:/usr/local/opt/numpy/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by sandcobainer** [comment] 2019-10-14 04:48
I can confirm adding PYTHON_PATH to `~/.bash_profile` doesn't solve the problem. I haven't found any other resources to install Swig as a python package either.

**Comment by dbogdanov** [comment] 2020-05-29 00:09
Closing as outdated (cannot reproduce the issue). We've updated Eigen dependency in Gaia. Also, swig is installed as a dependency in the gaia homebrew formula.

**Closed by dbogdanov** 2020-05-29 00:09 UTC
