### ISSUE TITLE
Unclear documentation for ConstantQ algorithm

### ISSUE THREAD

**Issue by pabloEntropia** [MTG/essentia#834] opened 2019-03-01 18:11 UTC
The documentation of [ConstantQ](https://essentia.upf.edu/documentation/reference/streaming_ConstantQ.html) is inexact. The description says,

>  algorithm implements Constant Q Transform using the FFT for fast calculation

 while the FFT is only used to compute the kernels, but the FFT of the input frames should be computed externally by the user. Also, the input description is 

> the input frame (complex)

and it may not be clear that the expected input is the FFT transform (both positive and negative frequencies) of the audio frame.

Following this, the [SpectrumCQ](https://essentia.upf.edu/documentation/reference/streaming_SpectrumCQ.html) input description is

> the input audio frame

but it is just a wrapper that casts a real vector into a complex one in order to run `ConstantQ`. This is incorrect because we are missing to take the FFT of the input audio frame.

I propose the following:
1. Modify `ConstantQ` to take audio frames as input and perform FFT inside as this is the intuitive behavior to expect.
2. Modify `SpectrumCQ`  to be a wrapper of `ConstantQ` that simply returns the magnitude of the `ConstantQ` output.
3. Create a python wrapper in `pytools` to perform `SpectrumCQ` in a frame-wise manner. Maybe something like `qcgram`?

**Comment by dbogdanov** [comment] 2019-03-04 13:58
1. The FFT was most probably kept outside of the ConstantQ algorithm so that the same FFT can be reused for different purposes (e.g., compute CQ and compute Mel bands). This makes sense for feature extractors, although we can't say how often it will be used in practise.

2. SpectrumCQ was intended to be a wrapper that includes FFT inside (just like Spectrum algorithm does).

3. Yes, we should add a ``cqgram``!

**Comment by pabloEntropia** [comment] 2019-03-06 10:29
1. Yes, the FFT algorithm should be kept outside `ConstantQ`, but still, I don't see the point of the `ConstantQ` algorithm taking the Complex FFT (including negative frequencies) as input. The reason is that this input is not straight-forward to obtain in Essentia and also it is not reusable for any other algorithm as far as I know.
2. In any case, we should modify `SpectrumCQ` to actually be a CQ version of Spectrum.

**Comment by dbogdanov** [comment] 2019-03-06 12:47
After a discussion, the solution will be: 
- Rename what is currently called a ```ConstantQ``` algorithm to ```ConstantQKernels ```
- New ```ConstantQ``` algorithm will accept  ```vector<Real>``` as an input and output complex value (similar to ```FFT```) and run this auxiliary algorithm inside.
- ```SpectrumCQ``` algorithm will be a wrapper of ```ConstantQ``` that outputs ```vector<Real>``` magnitudes (similar to ```Spectrum```)
- Make ```Chromogram``` a wrapper of ```SpectrumCQ``` that summarizes magnitudes into chroma bins.

**Comment by dbogdanov** [comment] 2019-08-01 14:44
> The reason is that this input is not straight-forward to obtain in Essentia and also it is not reusable for any other algorithm as far as I know.

This is actually now possible. Just thinking whether it is good to not provide an option to re-use the same FFT computation for multiple algorithms.

**Comment by dbogdanov** [comment] 2019-08-01 14:57
This is addressed in #890.

**Closed by dbogdanov** 2019-08-01 14:57 UTC
Labels: documentation, enhancement
